#postgresql configuration

spring.datasource.url=jdbc:postgresql://dpg-d22b6fe3jp1c738n56k0-a.oregon-postgres.render.com/moneymanager_ddu3
spring.datasource.username=moneymanager_ddu3_user
spring.datasource.password=IOaOA1fadAZLk5hKgioRBCuvhWxIlam6
spring.datasource.driver-class-name=org.postgresql.Driver