
#mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/moneymanager
spring.datasource.username=root
spring.datasource.password=saishiva12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#appended with the rest api calls
server.servlet.context-path=/api/v1.0


#jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#use to format the sql queries
spring.jpa.properties.hibernate.format_sql=true

#email configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${MAIL_FROM}

#providing the jwt secret
jwt.secret=U2Fpc2hpdmFTZWN1cmVLZXlAMTIzI0p3dFNlY3VyZQ==

#providing the frontend url
money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL}

#adding the prod properties and activating it
#so that the application will run in production mode
#this will be used to load the prod specific properties
spring.profiles.active=prod

#adding the backend url
app.activation.url=${MONEY_MANAGER_BACKEND_URL}


