#postgresql configuration

spring.datasource.url=jdbc:postgresql://pg-3b3ba40-saishivathatipalli-6025.d.aivencloud.com/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_SD_vE63R0pW4PQEn7ZV
spring.datasource.driver-class-name=org.postgresql.Driver
